### ISSUE TITLE
getInitialProps in _app.js

### ISSUE THREAD

**Issue by bkspace** [MathewsJoseph25/create-shopify-app#2]
Hi @MathewsJoseph25. Great that you have open sourced this example. There is a small caveat which I think could be worth mentioning in the docs, as a discussion point.

When you use getInitialProps in the _app.js, you tell next.js to SSR all pages and so ALL pages you have will lose the benefits of static rendering/CDN.

NextJS provides `getStaticProps` and `getServerSideProps` as an alternative, but you cannot use it on `_app.js` (yet...).

You could instead do `getStaticProps` on each page, and use `getServerSideProps` on pages which require server side rendering (for example to fetch some initial data!).

^ this would also not be ideal for shopify apps which have many, many pages for example

**Comment by MathewsJoseph25** [comment]
Hey @bkspace ! Thanks for the feedback buddy. I have updated the file for complete static rendering. Please have a look.

**Comment by bkspace** [comment]
Hey mate! IMO that's definitely a better way to do it, but I still think the patterns are a bit strange (suggested by Shopify).

For the api calls, you should be able to get the shop from JWT token, rather than using the shop from the window object (stopping any malicious users, although will there be any here?)

**Comment by MathewsJoseph25** [comment]
Actually, the shop param that's being stored in the window object isn't used for authentication on the server. Authentication is done using the shop param from the jwt only. The shop object in window is just to store the shop param globally across the frontend of the app, so that we can use that to redirect to other pages of the app by adding the shop param to the url. This is being done just so that when you do changes on the express app, the whole next app will be reloaded and in that case, if the shop param isn't available in the url, we won't know which shop param to set in the app bridge sdk. So, it's just for the development purpose, when full page reload needs to be considered. Let me know if you have any doubts.

**Comment by bkspace** [comment]
Sure that makes sense, and I've definitely run into that - refreshing the page means your Iframe is reloaded and you get the shop param, which hasn't been massively painful for me. No doubts, I understand, I just wouldn't do that myself ;)

**Comment by bkspace** [comment]
Closing as questions were answered 💯

**Comment by MathewsJoseph25** [comment]
Hey @bkspace! I was not talking about the whole page refresh which we manually do. In this case, Shopify will add the shop param and we don't have to take care of that. Rather, I was talking about the **AUTOMATIC FULL PAGE RELOAD** by NextJs whenever we reload the server (in our case, whenever we do changes to the express app, then, nodemon does this). In this type of reload, Shopify won't add any shop param and in our normal routes, if we don't add shop param ourselves, we won't know on the _app.js which shop is this and so, we can't init the app bridge. So, to overcome this case, I'm adding the shop param to all page redirects within the app using the window.shop object. So, in this case, we would get the shop param always on the url, even on NEXT.JS Automatic Reload. 

So, if you prefer doing a full page manual reload only, then, you don't need that object.
